typedef double real;
typedef double reala;

typedef struct struct_plmd {
  int nblocks;
  int nsites;
  int nsubsmax;
  int *nsubs;
  int *nsubs_d;
  int *block0;
  int *block0_d;
  int *block2site;
  real kh;
  real kJ;
  real *h;
  real *h_d;
  // cudaTextureObject_t h_tex;
  real *J;
  real *J_d;
  // cudaTextureObject_t J_tex;
  real *dhds;
  real *dhds_d;
  // cudaTextureObject_t dhds_tex;
  real *dJds;
  real *dJds_d;
  // cudaTextureObject_t dJds_tex;
  reala *dLdh;
  reala *dLdh_d;
  reala *dLdJ;
  reala *dLdJ_d;
  int *Seq;
  int *Seq_d;
  FILE *Seq_fp;
  int B;
  real *heff;
  real *heff_d;
  real *dheffds;
  real *dheffds_d;
  int Jend;
  real *x;
  reala *dLdx;
  // real *Hinv;
  int Nmemax;
  int Nmem;
  real *d_x;
  real *d_dLdx;
  real *rho;
  real *alpha;
  real *beta;
  real *hi;
  real *x0;
  reala *dLdx0;
  reala *L;
  reala *L_d;
  reala *dLds;
  reala *dLds_d;
// Control
  bool done;
  int iB;
  int BiB;
  int BiBmax;
} struct_plmd;

