#! /bin/bash

source modules

OPTIONS="--nodes=1 --tasks-per-node=1 -p gpu --gres=gpu:gtx1080:1 --time=2880 -o $DATDIR/slurm-%j.out -e $DATDIR/slurm-%j.out"
DEPEND="--dependency="

# rm ../Filter.dat
NB=50

for p in `seq 0 $(( $NB - 1 ))`
do

ARG="$DATDIR/h.bs$p.PLM.dat $DATDIR/J.bs$p.PLM.dat `awk '{print "'$DATDIR'/Filter."$1".dat"}' $DATDIR/bs$p.dat`"
PID=`sbatch $OPTIONS ./PLM.sh $ARG | awk '{print $4}'`
echo $PID
DEPEND="${DEPEND}afterany:$PID,"

done

ARG="$DATDIR/h.PLM.dat $DATDIR/J.PLM.dat `ls $DATDIR/Filter.*.dat`"
PID=`sbatch $OPTIONS ./PLM.sh $ARG | awk '{print $4}'`
echo $PID
DEPEND="${DEPEND}afterany:$PID"

OPTIONS="--nodes=1 --tasks-per-node=1 -p brooks --time=2880 -o $DATDIR/slurm-%j.out -e $DATDIR/slurm-%j.out"
sbatch $OPTIONS $DEPEND -W --wrap="sleep 30"
echo "Done with PLM"


